// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxFtSBZ35mJfeZ32Rlyw0UMMO68o68URA',
    appId: '1:500482957817:web:e31f91c686b51b31799d28',
    messagingSenderId: '500482957817',
    projectId: 'interfon-17107',
    authDomain: 'interfon-17107.firebaseapp.com',
    databaseURL: 'https://interfon-17107-default-rtdb.firebaseio.com',
    storageBucket: 'interfon-17107.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAABnb-nNsBwyFmPsjHeu48BzIwbAPQSwo',
    appId: '1:500482957817:android:c179fd5b716b2f49799d28',
    messagingSenderId: '500482957817',
    projectId: 'interfon-17107',
    databaseURL: 'https://interfon-17107-default-rtdb.firebaseio.com',
    storageBucket: 'interfon-17107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs7wA4cmKCvPKRnF8zFzLqIjSl-LyWQu0',
    appId: '1:500482957817:ios:b152cc2d36d52ade799d28',
    messagingSenderId: '500482957817',
    projectId: 'interfon-17107',
    databaseURL: 'https://interfon-17107-default-rtdb.firebaseio.com',
    storageBucket: 'interfon-17107.appspot.com',
    iosClientId:
        '500482957817-5v908g2m386a7ompclm7rgttmciaqmm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.primeiroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs7wA4cmKCvPKRnF8zFzLqIjSl-LyWQu0',
    appId: '1:500482957817:ios:b152cc2d36d52ade799d28',
    messagingSenderId: '500482957817',
    projectId: 'interfon-17107',
    databaseURL: 'https://interfon-17107-default-rtdb.firebaseio.com',
    storageBucket: 'interfon-17107.appspot.com',
    iosClientId:
        '500482957817-5v908g2m386a7ompclm7rgttmciaqmm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.primeiroApp',
  );
}
